---
- fail:
    msg: "This OS is not supported."
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '6'

- name: Import distribution specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: check required params
  fail:
    msg: "{{ item }} needs to have something"
  when: "{{ item }} == None or {{ item }} is undefined"
  with_items:
    - jenkins_repo_url
    - jenkins_package_key
    - jenkins_java_pkg_name
